import { useEffect, useMemo, useState } from "react";
import { FiAlertTriangle, FiCheck, FiDatabase, FiUploadCloud } from "react-icons/fi";
import api from "../services/api";
import { parseContentFile } from "./admin/contentFile";
import "../Styles/AdminOffers.css";

const statusCopy = { accepted: "Ready", ambiguous: "Review", unmatched: "No match", rejected: "Rejected" };

const AdminContent = () => {
  const [observations, setObservations] = useState([]);
  const [fileName, setFileName] = useState("");
  const [preview, setPreview] = useState(null);
  const [history, setHistory] = useState([]);
  const [state, setState] = useState("idle");
  const [message, setMessage] = useState("");

  const loadHistory = async () => {
    try {
      const response = await api.get("/api/v1/admin/content/history");
      setHistory(response.data.data || []);
    } catch { setHistory([]); }
  };
  useEffect(() => { loadHistory(); }, []);

  const handleFile = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;
    setPreview(null);
    setMessage("");
    try {
      const payload = await parseContentFile(file);
      if (payload.observations.length > 500) throw new Error("A content feed can contain at most 500 observations");
      setObservations(payload.observations);
      setFileName(file.name);
    } catch (error) {
      setObservations([]);
      setFileName("");
      setMessage(error.message || "Unable to read this content feed");
    }
  };

  const previewFeed = async (event) => {
    event.preventDefault();
    setState("previewing");
    setMessage("");
    try {
      const response = await api.post("/api/v1/admin/content/preview", { observations });
      setPreview(response.data.data);
      setState("ready");
    } catch (error) {
      setPreview(null);
      setState("error");
      setMessage(error.response?.data?.error || "The content feed could not be reviewed");
    }
  };

  const applyFeed = async () => {
    setState("applying");
    setMessage("");
    try {
      const response = await api.post("/api/v1/admin/content/apply", { observations, previewToken: preview.previewToken });
      const applied = response.data.data?.counts?.applied || 0;
      setState("applied");
      setMessage(response.data.replay ? "This exact evidence feed was already applied." : `${applied} new evidence observation${applied === 1 ? "" : "s"} promoted.`);
      await loadHistory();
    } catch (error) {
      setState("error");
      setMessage(error.response?.data?.error || "The content feed could not be applied");
    }
  };

  const accepted = useMemo(() => preview?.rows?.filter((row) => row.status === "accepted") || [], [preview]);
  return (
    <div className="offer-admin-page">
      <header className="offer-admin-hero">
        <div><p className="ui-kicker">Catalog evidence operations</p><h1>Promote content without rewriting truth.</h1><p>Review immutable Open Icecat observations against exact manufacturer part numbers. Approved evidence remains separate from compatibility specifications and retailer prices.</p></div>
        <div className="offer-admin-rule"><FiDatabase aria-hidden="true" /><strong>Exact identity matches only</strong><span>No fuzzy names, price changes, or compatibility-field overwrites.</span></div>
      </header>
      <div className="offer-admin-layout">
        <form className="offer-upload-panel" onSubmit={previewFeed}>
          <div className="offer-panel-heading"><div><span>01</span><h2>Load evidence</h2></div></div>
          <label className="offer-dropzone"><FiUploadCloud aria-hidden="true" /><strong>{fileName || "Choose Open Icecat JSON"}</strong><span>{observations.length ? `${observations.length} observations loaded` : "Generated by npm run catalog:content:export"}</span><input type="file" accept=".json,application/json" onChange={handleFile} required /></label>
          <button className="offer-primary" type="submit" disabled={!observations.length || state === "previewing" || state === "applying"}>{state === "previewing" ? "Reviewing…" : "Preview exact matches"}</button>
          {message ? <p className={`offer-message ${state === "error" ? "error" : "success"}`} role="status">{message}</p> : null}
        </form>
        <section className="offer-review-panel" aria-labelledby="content-review-title">
          <div className="offer-panel-heading"><div><span>02</span><h2 id="content-review-title">Review evidence</h2></div>{preview ? <code>{preview.checksum.slice(0, 10)}</code> : null}</div>
          {!preview ? <div className="offer-empty"><FiAlertTriangle aria-hidden="true" /><strong>No preview yet</strong><span>Load the exported feed to inspect exact matches and rejected observations.</span></div> : <>
            <dl className="offer-counts"><div><dt>Ready</dt><dd>{preview.counts.accepted}</dd></div><div><dt>Review</dt><dd>{preview.counts.ambiguous}</dd></div><div><dt>No match</dt><dd>{preview.counts.unmatched}</dd></div><div><dt>Rejected</dt><dd>{preview.counts.rejected}</dd></div></dl>
            <div className="offer-table-wrap"><table className="offer-table"><thead><tr><th>Status</th><th>Source product</th><th>Catalog match</th><th>Evidence</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.observation.observation_id}><td><span className={`offer-status ${row.status}`}>{row.status === "accepted" ? <FiCheck aria-hidden="true" /> : null}{statusCopy[row.status]}</span></td><td><strong>{row.observation.name}</strong><small>{row.observation.manufacturer_part_number}</small></td><td>{row.match ? <><strong>{row.match.name}</strong><small>Exact manufacturer part number</small></> : <strong>{row.reason || row.errors?.join(" · ")}</strong>}</td><td><strong>{Object.keys(row.observation.specifications || {}).length} fields</strong><small>{row.observation.gtins.length} GTINs</small></td></tr>)}</tbody></table></div>
            <div className="offer-apply-bar"><span>{accepted.length} exact match{accepted.length === 1 ? "" : "es"} can be promoted. Other rows remain unchanged.</span><button className="offer-primary" type="button" onClick={applyFeed} disabled={!accepted.length || state === "applying" || state === "applied"}>{state === "applying" ? "Applying…" : state === "applied" ? "Applied" : "Promote reviewed evidence"}</button></div>
          </>}
        </section>
      </div>
      <section className="offer-history"><div className="offer-panel-heading"><div><span>03</span><h2>Recent content promotions</h2></div></div>{history.length ? <div className="offer-history-list">{history.map((batch) => <article key={batch._id}><strong>{batch.source}</strong><span>{new Date(batch.createdAt).toLocaleString()}</span><span>{batch.counts.applied} applied</span><code>{batch.checksum.slice(0, 10)}</code></article>)}</div> : <p>No product-content evidence has been promoted yet.</p>}</section>
    </div>
  );
};

export default AdminContent;
